SELECT D.AUTHOR_ID, D.AUTHOR_NAME, D.CATEGORY, SUM(D.TOTAl_SALES) AS TOTAl_SALES
FROM
(SELECT B.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY, SUM(A.SALES) * B.PRICE AS TOTAL_SALES
FROM BOOK_SALES AS A JOIN BOOK AS B JOIN AUTHOR AS C
WHERE A.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    AND A.BOOK_ID = B.BOOK_ID
    AND B.AUTHOR_ID = C.AUTHOR_ID
GROUP BY A.BOOK_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC) AS D
GROUP BY D.AUTHOR_ID, D.CATEGORY
;