SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_INFO C
WHERE C.ITEM_ID NOT IN (SELECT A.ITEM_ID
     FROM ITEM_TREE A JOIN ITEM_TREE B
     WHERE A.ITEM_ID = B.PARENT_ITEM_ID
     GROUP BY A.ITEM_ID)
ORDER BY C.ITEM_ID DESC
;