SELECT DISTINCT CAR_ID,
CASE
    WHEN CAR_ID IN (SELECT A.CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
                    WHERE A.START_DATE <= "2022-10-16" AND A.END_DATE >= "2022-10-16")
    THEN "대여중"
    ELSE "대여 가능"
END AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY CAR_ID DESC
;