SELECT TT.FLAVOR AS FLAVOR
FROM
(SELECT A.FLAVOR, (AF + BF) AS FF
FROM
    (SELECT FLAVOR, SUM(TOTAL_ORDER) AS AF
     FROM FIRST_HALF
     GROUP BY FLAVOR
    ) A JOIN
    (SELECT FLAVOR, SUM(TOTAL_ORDER) AS BF
     FROM JULY
     GROUP BY FLAVOR
    ) B
ON A.FLAVOR = B.FLAVOR
GROUP BY A.FLAVOR
ORDER BY FF DESC) TT
LIMIT 3