SELECT MONTH(start_date) AS MONTH, C.car_id AS CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C,
    (SELECT *
    FROM 
        (SELECT car_id, COUNT(*) AS MONTH_COUNT
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE MONTH(start_date) BETWEEN 8 AND 10
        GROUP BY car_id) AS A
    WHERE MONTH_COUNT >= 5) AS B
WHERE C.car_id = B.car_id AND MONTH(start_date) BETWEEN 8 AND 10
GROUP BY C.car_id, MONTH(start_date)
ORDER BY MONTH, CAR_ID DESC
;