SELECT B.YEAR, (B.SIZE_OF_COLONY - A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
FROM ECOLI_DATA A JOIN
    (SELECT MAX(SIZE_OF_COLONY) AS SIZE_OF_COLONY, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)) B
ON DATE_FORMAT(A.DIFFERENTIATION_DATE, '%Y') = B.YEAR
ORDER BY B.YEAR, YEAR_DEV
;