SELECT C.ID, A.FISH_NAME, B.LENGTH
FROM FISH_NAME_INFO A JOIN 
    (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE) B JOIN FISH_INFO C
ON A.FISH_TYPE = B.FISH_TYPE AND B.FISH_TYPE = C.FISH_TYPE AND B.LENGTH = C.LENGTH
;