SELECT A.CATEGORY CATEGORY, SUM(B.SALES) TOTAL_SALES
FROM BOOK A JOIN
    (SELECT BOOK_ID, SUM(SALES) SALES
    FROM BOOK_SALES
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY BOOK_ID) B
ON A.BOOK_ID = B.BOOK_ID
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY
;