SELECT B.CATEGORY, B.PRICE AS MAX_PRICE, B.PRODUCT_NAME
FROM (SELECT MAX(PRICE) AS PRICE, CATEGORY
     FROM FOOD_PRODUCT
     GROUP BY CATEGORY) A JOIN FOOD_PRODUCT B
ON A.PRICE = B.PRICE AND A.CATEGORY = B.CATEGORY
WHERE B.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC
;